{ 
    status: 200,
    statusText: 'OK',
    headers: 
     { server: 'openresty',
       date: 'Sat, 24 Mar 2018 03:12:05 GMT',
       'content-type': 'application/json; charset=utf-8',
       'content-length': '455',
       connection: 'close',
       'x-cache-key': '/data/2.5/weather?APPID=a90a1769668d41f38e80d8ee118e7760&zip=84109,us',
       'access-control-allow-origin': '*',
       'access-control-allow-credentials': 'true',
       'access-control-allow-methods': 'GET, POST' },
    config: 
     { adapter: [Function: httpAdapter],
       transformRequest: { '0': [Function: transformRequest] },
       transformResponse: { '0': [Function: transformResponse] },
       timeout: 0,
       xsrfCookieName: 'XSRF-TOKEN',
       xsrfHeaderName: 'X-XSRF-TOKEN',
       maxContentLength: -1,
       validateStatus: [Function: validateStatus],
       headers: 
        { Accept: 'application/json, text/plain, */*',
          'User-Agent': 'axios/0.18.0' },
       method: 'get',
       url: 'http://api.openweathermap.org/data/2.5/weather?zip=84109,us&APPID=a90a1769668d41f38e80d8ee118e7760',
       data: undefined },
    request: 
     ClientRequest {
       domain: null,
       _events: 
        { socket: [Function],
          abort: [Function],
          aborted: [Function],
          error: [Function],
          timeout: [Function],
          prefinish: [Function: requestOnPrefinish] },
       _eventsCount: 6,
       _maxListeners: undefined,
       output: [],
       outputEncodings: [],
       outputCallbacks: [],
       outputSize: 0,
       writable: false,
       _last: true,
       upgrading: false,
       chunkedEncoding: false,
       shouldKeepAlive: false,
       useChunkedEncodingByDefault: false,
       sendDate: false,
       _removedConnection: false,
       _removedContLen: false,
       _removedTE: false,
       _contentLength: 0,
       _hasBody: true,
       _trailer: '',
       finished: true,
       _headerSent: true,
       socket: 
        Socket {
          connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: 'api.openweathermap.org',
          _readableState: [Object],
          readable: false,
          domain: null,
          _events: [Object],
          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: [Object],
          writable: false,
          allowHalfOpen: false,
          _bytesDispatched: 204,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular],
          read: [Function],
          _consuming: true,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1,
          [Symbol(asyncId)]: 8,
          [Symbol(bytesRead)]: 814 },
       connection: 
        Socket {
          connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: 'api.openweathermap.org',
          _readableState: [Object],
          readable: false,
          domain: null,
          _events: [Object],
          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: [Object],
          writable: false,
          allowHalfOpen: false,
          _bytesDispatched: 204,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular],
          read: [Function],
          _consuming: true,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1,
          [Symbol(asyncId)]: 8,
          [Symbol(bytesRead)]: 814 },
       _header: 'GET /data/2.5/weather?zip=84109,us&APPID=a90a1769668d41f38e80d8ee118e7760 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: api.openweathermap.org\r\nConnection: close\r\n\r\n',
       _onPendingData: [Function: noopPendingOutput],
       agent: 
        Agent {
          domain: null,
          _events: [Object],
          _eventsCount: 1,
          _maxListeners: undefined,
          defaultPort: 80,
          protocol: 'http:',
          options: [Object],
          requests: {},
          sockets: {},
          freeSockets: {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256 },
       socketPath: undefined,
       timeout: undefined,
       method: 'GET',
       path: '/data/2.5/weather?zip=84109,us&APPID=a90a1769668d41f38e80d8ee118e7760',
       _ended: true,
       res: 
        IncomingMessage {
          _readableState: [Object],
          readable: false,
          domain: null,
          _events: [Object],
          _eventsCount: 3,
          _maxListeners: undefined,
          socket: [Object],
          connection: [Object],
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: true,
          headers: [Object],
          rawHeaders: [Array],
          trailers: {},
          rawTrailers: [],
          upgrade: false,
          url: '',
          method: null,
          statusCode: 200,
          statusMessage: 'OK',
          client: [Object],
          _consuming: true,
          _dumped: false,
          req: [Circular],
          responseUrl: 'http://api.openweathermap.org/data/2.5/weather?zip=84109,us&APPID=a90a1769668d41f38e80d8ee118e7760',
          read: [Function] },
       aborted: undefined,
       timeoutCb: null,
       upgradeOrConnect: false,
       parser: null,
       maxHeadersCount: null,
       _redirectable: 
        Writable {
          _writableState: [Object],
          writable: true,
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          _options: [Object],
          _redirectCount: 0,
          _requestBodyLength: 0,
          _requestBodyBuffers: [],
          _onNativeResponse: [Function],
          _currentRequest: [Circular],
          _currentUrl: 'http://api.openweathermap.org/data/2.5/weather?zip=84109,us&APPID=a90a1769668d41f38e80d8ee118e7760' },
       [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
    data: 
     { coord: { lon: -111.82, lat: 40.67 },
       weather: [ [Object] ],
       base: 'stations',
       main: 
        { temp: 283.56,
          pressure: 1015,
          humidity: 66,
          temp_min: 282.15,
          temp_max: 287.15 },
       visibility: 16093,
       wind: { speed: 2.1, deg: 230 },
       clouds: { all: 1 },
       dt: 1521858900,
       sys: 
        { type: 1,
          id: 2828,
          message: 0.0044,
          country: 'US',
          sunrise: 1521897818,
          sunset: 1521942232 },
       id: 420037374,
       name: 'Salt Lake City',
       cod: 200 
    } 
}
  

// --------------------------------------------
// =============================================


response.status 200

response.data.name 
response.data.weather[0].description  "clear sky"
response.data.main: 
                    humidity:65
                    pressure:1015
                    temp:281.92
                    temp_max:286.15
                    temp_min:280.15
response.data.wind.speed
response.data.

